version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: carsrental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: carsrental
      MYSQL_USER: carsrental_user
      MYSQL_PASSWORD: carsrental_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: